name: running linter and tests
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'accessible'
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '16.x'

      - name: 'installation'
        run: npm ci
      
      - name: 'linter-check'
        run: npx eslint .
      
      - name: 'run tests'
        run: npx jest

      - name: 'publish code coverage'
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
